steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/fitsync-backend/fitsync-backend", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/fitsync-backend/fitsync-backend"]

images:
  - "gcr.io/fitsync-backend/fitsync-backend"
